### ISSUE TITLE
MA3 Patch, results in broken external player

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/animeplugin3#15] opened 2014-08-20 06:18 UTC
**Reported by andyieg.andreas, Mar 3, 2014**

**What steps will reproduce the problem?**
Replace the Anime.dll, with the version from the patch.

I guess this patch is only for certain users, since it breaks my setup. So a more descriptive text for the patch would be nice.

**Comment by ElementalCrisis** [comment] 2016-09-03 15:29
I'm going to close this as it's was for an older version, if the problem is still present then comment in this thread.

**Closed by ElementalCrisis** 2016-09-03 15:29 UTC
Labels: Bug - High Priority
